// state 1 - not Started
export const NOT_STARTED = 'NOT_STARTED';

export const CLOSEDPO_DATE_RANGE_NOT_READY = 'CLOSEDPO_DATE_RANGE_NOT_READY';
export const CLOSEDPO_DATE_RANGE_READY = 'CLOSEDPO_DATE_RANGE_READY';
export const CLOSEDPO_DATE_RANGE_NO_RECORDS = 'CLOSEDPO_DATE_RANGE_NO_RECORDS';

export const NORECEIVERS_DATE_RANGE_NOT_READY = 'NORECEIVERS_DATE_RANGE_NOT_READY';
export const NORECEIVERS_DATE_RANGE_READY = 'NORECEIVERS_DATE_RANGE_READY';
export const NORECEIVERS_DATE_RANGE_NO_RECORDS = 'NORECEIVERS_DATE_RANGE_NO_RECORDS';

export const OPENPO_NO_RECORDS = 'OPENPO_NO_RECORDS';
export const OPENPO_DATE_RANGE_NOT_READY = 'OPENPO_DATE_RANGE_NOT_READY';
export const OPENPO_DATE_RANGE_READY = 'OPENPO_DATE_RANGE_READY';
export const OPENPO_DATE_RANGE_NO_RECORDS = 'OPENPO_DATE_RANGE_NO_RECORDS';

export const PO_PROMPT_NOT_READY = 'PO_PROMPT_NOT_READY';
export const PO_PROMPT_READY = 'PO_PROMPT_READY';

/// state 3 - started
export const STARTED = 'STARTED';
// state 90 - FAILED
export const FAILURE = 'FAILURE';
// state 100 - Completed successfully
export const SUCCESS = 'SUCCESS';