
export const CANCEL_APP = 'RPT_CANCEL_APP';

export const INIT = 'RPT_INIT';
export const INIT_NO_STATE = 'RPT_INIT_NO_STATE';

export const OPENPO_EMAIL_MRO_TOGGLE ='RPT_OPENPO_EMAIL_MRO_TOGGLE';
export const OPENPO_EMAIL_VENDOR_TOGGLE = 'RPT_OPENPO_EMAIL_VENDOR_TOGGLE';

export const OPENPO_PAGER_DONE = 'RPT_OPENPO_PAGER_DONE';
export const OPENPO_PAGER_FAILED = 'RPT_OPENPO_PAGER_FAILED';


export const SET_CLOSEDPO_DATE_HEADER = 'RPT_SET_CLOSEDPO_DATE_HEADER';
export const SET_CLOSEDPO_DATE_START = 'RPT_SET_CLOSEDPO_DATE_START';
export const SET_CLOSEDPO_DATE_END = 'RPT_SET_CLOSEDPO_DATE_END';
export const SET_CLOSEDPO_REPORT_DONE = 'RPT_SET_CLOSEDPO_REPORT_DONE';
export const SET_CLOSEDPO_REPORT_FAILED = 'RPT_CLOSEDPO_REPORT_FAILED';

export const SET_NORECEIVERS_DATE_HEADER = 'RPT_SET_NORECEIVERS_DATE_HEADER';
export const SET_NORECEIVERS_DATE_START = 'RPT_SET_NORECEIVERS_DATE_START';
export const SET_NORECEIVERS_DATE_END = 'RPT_SET_NORECEIVERS_DATE_END';
export const SET_NORECEIVERS_REPORT_DONE = 'RPT_SET_NORECEIVERS_REPORT_DONE';
export const SET_NORECEIVERS_REPORT_FAILED = 'RPT_NORECEIVERS_REPORT_FAILED';


export const SET_OPENPO_DATE_HEADER = 'RPT_SET_OPENPO_DATE_HEADER';
export const SET_OPENPO_DATE_START = 'RPT_SET_OPENPO_DATE_START';
export const SET_OPENPO_DATE_END = 'RPT_SET_OPENPO_DATE_END';
export const SET_OPENPO_EMAIL_HEADER = 'RPT_SET_OPENPO_EMAIL_HEADER';

export const SET_OPENPO_CURPAGE = 'RPT_SET_OPENPO_CURPAGE';
export const SET_OPENPO_MAXPAGE = 'RPT_SET_OPENPO_MAXPAGE';
export const SET_OPENPO_NEXTPAGE = 'RPT_SET_OPENPO_NEXTPAGE';
export const SET_OPENPO_PO = 'RPT_SET_OPENPO_PO';
export const SET_OPENPO_POITEM = 'RPT_SET_OPENPO_POITEM';
export const SET_OPENPO_PREVPAGE = 'RPT_SET_OPENPO_PREVPAGE';
export const SET_OPENPO_SELECT = 'RPT_SET_OPENPO_SELECT';

export const SET_PRODUCTS_CATEGORY_STYLE = 'RPT_SET_PRODUCTS_CATEGORY_STYLE';

export const SET_PROGRESS_BTN = 'RPT_SET_PROGRESS_BTN';

export const SET_POSTATUS_REPORT_PDF = 'RPT_SET_POSTATUS_REPORT_PDF';
export const SET_POSTATUS_REPORT_DONE = 'RPT_SET_POSTATUS_REPORT_DONE';
export const SET_POSTATUS_REPORT_FAILED = 'RPT_SET_POSTATUS_REPORT_FAILED';

export const SET_REASON = 'RPT_SET_REASON';
export const SET_STATE = 'RPT_SET_STATE';
export const SET_STATUS = 'RPT_SET_STATUS';

export const SQL_OPENPO_DONE = 'RPT_SQL_OPENPO_DONE';
export const SQL_OPENPO_FAILED = 'RPT_SQL_OPENPO_FAILED';
export const SQL_OPENPO_VENDOR_EMAIL_DONE = 'RPT_SQL_OPENPO_VENDOR_EMAIL_DONE';
export const SQL_OPENPO_VENDOR_EMAIL_FAILED = 'RPT_SQL_OPENPO_VENDOR_EMAIL_FAILED';

export const TOGGLE_OPEN_PO_SELECTED = 'RPT_TOGGLE_OPEN_PO_SELECTED';
export const TOGGLE_OPEN_PO_VISIBLE = 'RPT_TOGGLE_OPEN_PO_VISIBLE';

